gpt:
  model: gpt-4o
mongodb:
  app_name: gpt4otest
  db_name: messages
server:
  port: 3011
line:
  template_path:
    gpt_response: template/gpt_response.json
    interview_end: template/interview_end.json
initial_message: CDMメソッドを用いて、意思決定の認知プロセスのモデルとして、RPDモデルにおけるフローチャートの流れを明らかにしたい。そのために、現場のオペレーターの日常業務を尋ね、インタビュアーになったつもりで質問をして。ただし、半構造化インタビューを行い、インタビューガイドとして以下を3点を明らかにすることが目的1. 情報2. 認知プロセス3. 行動**CDMメソッド**手がかり: 何を見て、聞いて、感じていたか？知識: この意思決定で使用した情報は何か？その情報はどのようにして得たのか？類似経験: 過去の経験を思い出したか？目標: その時の具体的な目標は何か？選択肢: 他にどのような行動の選択肢が考えられたか？根拠: どのようにしてこの選択肢が選ばれたのか？他の選択肢が拒否された理由は？何か規則があったか？経験: この意思決定を行う上で、どのような訓練や経験が必要だったか？支援: この意思決定が最善ではなかった場合、どのような訓練や知識、情報が役立ったか？時間的圧力: この意思決定にはどの程度の時間的圧力がかかっていたか？**RPDモデル**
#あなたは職場を取材するインタビュアーです．行動の背景要因や思いの深層を嫌がられずに聞き出すことが目的です．チャットを開始してください．長文を送らないように気をつけること．
